### ISSUE TITLE
Failed installation on Darwin 

### ISSUE THREAD

**Issue by pfdamasceno** [grachev/node-lemmer#5]
Hi, I'm trying to install infranodus https://github.com/deemeetree/infranodus

They suggest downloading node-lemmer from github, followed by npm install node-lemmer/

I get the following error:

stack Error: `make` failed with exit code: 2
stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
stack     at emitTwo (events.js:87:13)
stack     at ChildProcess.emit (events.js:172:7)
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
System Darwin 14.5.0
command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
cwd /Users/damasceno/Downloads/infranodus-master/node_modules/node-lemmer
node -v v5.0.0
node-gyp -v v3.0.3
not ok
Darwin 14.5.0
argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install" "node-lemmer/"
node v5.0.0
npm  v3.3.9
code ELIFECYCLE

node-lemmer@0.1.0 install: `node-gyp rebuild`
Exit status 1

Failed at the node-lemmer@0.1.0 install script 'node-gyp rebuild'.
This is most likely a problem with the node-lemmer package,
not with npm itself.
Tell the author that this fails on your system:
    node-gyp rebuild
You can get their info via:
    npm owner ls node-lemmer
There is likely additional logging output above.

Any suggestion? 

I'm on OSX 10.10.5

**Comment by dromologue** [comment]
I had the same issue....
